site_name: Abies's Notebook
repo_url: https://github.com/Abiesjqq/Abies_Notebook
repo_name: Abies_Notebook
theme:
  name: material
  custom_dir: docs/scripts
  font:
    text: Roboto

  icon:
    logo: material/forest-outline

  language: zh

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: 切换至夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - announce.dismiss # 可关闭公告栏
    - navigation.instant # 页面无刷新切换
    - header.autohide # 自动隐藏头部
    - navigation.instant.progress # 页面切换进度条
    - navigation.prune # 只渲染可见导航项
    - navigation.tracking # 滚动时URL锚点自动更新
    - navigation.tabs # 一级导航显示为顶部Tab
    - navigation.tabs.sticky # Tab栏吸顶
    # - navigation.sections # 侧边栏分组
    - navigation.top # 返回顶部按钮
    - navigation.footer # 页脚显示在侧边栏
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - search.share # 搜索结果分享
    - toc.follow # 目录跟随滚动
    - toc.integrate # 目录集成到侧边栏
    - navigation.expand # 默认展开所有目录
    - navigation.indexes # 支持节索引页
    - content.tabs.link # 支持标签页链接
    - content.tooltips # 支持鼠标悬浮提示
    - content.code.copy # 代码块一键复制
    - content.code.select # 代码块一键全选
    # - content.action.edit # 编辑按钮
    # - content.action.view # 查看源码按钮
    - content.code.annotate # 代码注释
    - git-revision-date
    - git-revision-date-localized

hooks:
  - docs/scripts/hooks/reading_time.py

nav:
  - Home:
      - Homepage: index.md
      - Notebook介绍: 介绍/Notebook介绍.md
      - 通知公告:
          - 通知公告: notices/index.md
  - 碎碎念:
      - Python:
          - Numpy & Pandas: 自学记录/Python/Numpy & Pandas/Numpy & Pandas.md
          - Matplotlib: 自学记录/Python/Matplotlib/Matplotlib.md
          - Scikit-learn:
              - 入门: 自学记录/Python/Scikit-learn/入门/入门.md
              - 数据预处理: 自学记录/Python/Scikit-learn/数据预处理/数据预处理.md
              - 监督学习与无监督学习: 自学记录/Python/Scikit-learn/监督学习与无监督学习/监督学习与无监督学习.md
              - 支持向量机(SVM): 自学记录/Python/Scikit-learn/支持向量机/支持向量机.md
              - 随机森林: 自学记录/Python/Scikit-learn/随机森林/随机森林.md
              - 主成分分析: 自学记录/Python/Scikit-learn/主成分分析/主成分分析.md
              - K-Means 聚类: 自学记录/Python/Scikit-learn/K-Means聚类/K-Means聚类.md
          - Pytorch:
              - Tensors 入门: 自学记录/Python/PyTorch/Tensors入门/Tensors入门.md
              - 线性回归和逻辑回归: 自学记录/Python/PyTorch/线性回归和逻辑回归/线性回归和逻辑回归.md
              - MLP与CNN: 自学记录/Python/PyTorch/MLP与CNN/MLP与CNN.md
              - RNN与DQN: 自学记录/Python/PyTorch/RNN与DQN/RNN与DQN.md
      - Git: 自学记录/Git/git.md
      - MkDocs: 自学记录/MkDocs/mkdocs.md
      - CSS: 自学记录/CSS/css_learning.md
      - JavaScript: 自学记录/JavaScript/js_learning.md
      - R:
          - 基本数据处理: 自学记录/R/基本数据处理/基本数据处理.md
      - 数学:
          - 因果效应估计: 自学记录/数学/因果效应估计/因果效应估计.md
  - 课程笔记:
      - 数据结构基础:
          - 0. 数据结构复习: 课程笔记/数据结构基础/0. 期末复习.md
          - 1. 时间复杂度: 课程笔记/数据结构基础/1. 时间复杂度.md
          - 2. 最大连续和子数组: 课程笔记/数据结构基础/2. 最大连续和子数组.md
          - 3. 堆栈和队列: 课程笔记/数据结构基础/3. 堆栈和队列.md
          - 4. 树的概念: 课程笔记/数据结构基础/4. 树的概念.md
          - 5. 树的遍历和特殊的树: 课程笔记/数据结构基础/5. 树的遍历和特殊的树.md
          - 5.5 一些题目和笔记: 课程笔记/数据结构基础/5.5 一些题目和笔记.md
          - 6. 堆的实现: 课程笔记/数据结构基础/6. 堆的实现.md
          - 7. 并查集和图: 课程笔记/数据结构基础/7. 并查集和图.md
          - 8. 拓扑排序和Dijkstra: 课程笔记/数据结构基础/8. 拓扑排序和Dijkstra.md
          - 9. Floyd和AOE网: 课程笔记/数据结构基础/9. Floyd和AOE网.md
          - 10. 网络流问题和最小生成树: 课程笔记/数据结构基础/10. 网络流问题和最小生成树.md
          - 11. 双连通图和欧拉回路: 课程笔记/数据结构基础/11. 双连通图和欧拉回路.md
          - 12. 希尔，堆，归并，快速排序: 课程笔记/数据结构基础/12. 希尔，堆，归并，快速排序.md
          - 13. 循环不变式和区块链: 课程笔记/数据结构基础/13. 循环不变式和区块链.md
          - 14. 比特币和哈希: 课程笔记/数据结构基础/14. 比特币和哈希.md
          - 15. 哈希动态查找: 课程笔记/数据结构基础/15. 哈希动态查找.md
          - 15.5 一些代码: 课程笔记/数据结构基础/15.5 一些代码.md
      - C语言程序设计: 课程笔记/C语言程序设计/CNote.md
  - Noflower 的笔记:
      - Computer Vision （进行中）:
          - Intro & K-NN: NoflowersNotes/ComputerVision/Intro&K-NN.md
          - Loss Functions: NoflowersNotes/ComputerVision/Loss Functions.md
          - Gradient Descent: NoflowersNotes/ComputerVision/Gradient_Descent/Gradient_Descent.md
          - CNN & Training Basics: NoflowersNotes/ComputerVision/CNN/CNN.md
          - RNN: NoflowersNotes/ComputerVision/RNN/RNN.md
          - Detection, Segmentation, Visualization, and Understanding: NoflowersNotes/ComputerVision/DetectionandSegementation/DetectionandSegementation.md
          - Attention and Transformers: NoflowersNotes/ComputerVision/AttentionandTransformers/AttentionandTransformers.md
          - Video Understanding: NoflowersNotes/ComputerVision/VideoUnderstanding/VideoUnderstanding.md
      - 数模笔记:
          - 数模的概率统计笔记: NoflowersNotes/概率统计/数模的概率统计笔记.md
          - 微分方程: NoflowersNotes/数模/微分方程建模/微分方程建模.md
  - Abies 的笔记:
      - GAMES101(进行中):
          - Lecture 01 Overview of Computer Graphics: AbiesNotes/图形学入门/Lecture 01 Overview of Computer Graphics.md
          - Lecture 02 Review of Linear Algebra: AbiesNotes/图形学入门/Lecture 02 Review of Linear Algebra.md
          - Lecture 03 Transformation: AbiesNotes/图形学入门/Lecture 03 Transformation.md
          - Lecture 04 Transformations Cont.: AbiesNotes/图形学入门/Lecture 04 Transformations Cont.md
          - Lecture 05 Rasterization 1 (Triangles): AbiesNotes/图形学入门/Lecture 05 Rasterization 1 (Triangles).md
          - Lecture 06 Rasterization 2 (Antiliasing): AbiesNotes/图形学入门/Lecture 06 Rasterization 2 (Antiliasing).md
          - Lecture 07 Shading 1 (Illumination, Shading and Graphics Pipelines): AbiesNotes/图形学入门/Lecture 07 Shading 1.md
          - Lecture 08 Shading 2 (Shading, Pipeline and Texture Mapping): AbiesNotes/图形学入门/Lecture 08 Shading 2.md
          - Lecture 09 Shading 3 (Texture Mapping cont.): AbiesNotes/图形学入门/Lecture 09 Shading 3.md
          - Lecture 10 Geomertry 1 (Introduction): AbiesNotes/图形学入门/Lecture 10 Geometry 1.md
          - Lecture 11 Geomertry 2 (Curves and Surfaces): AbiesNotes/图形学入门/Lecture 11 Geometry 2.md
      - 渲染器tinyrenderer(进行中):
          - Getting started: AbiesNotes/渲染器tinyrenderer/getting started.md
          - Line: AbiesNotes/渲染器tinyrenderer/line.md
          - Triangle: AbiesNotes/渲染器tinyrenderer/triangle.md
          - Texture: AbiesNotes/渲染器tinyrenderer/texture.md
          - Projection: AbiesNotes/渲染器tinyrenderer/projection.md
          - Gourand Shading: AbiesNotes/渲染器tinyrenderer/Gourand.md
          - Camera: AbiesNotes/渲染器tinyrenderer/camera.md
          - Shader: AbiesNotes/渲染器tinyrenderer/shader.md
  - 论文阅读:
      - Diffusion:
          - Denoising Diffusion Probabilistic Models: 论文阅读/Diffusion/Denoising Diffusion Probabilistic Models/Denoising Diffusion Probabilistic Models.md
          - Denoising Diffusion Implicit Models: 论文阅读/Diffusion/Denoising Diffusion Implicit Models/Denoising Diffusion Implicit Models.md
          - Score-Based Generative Modeling through Stochastic Differential Equations: 论文阅读/Diffusion/Score-Based Generative Modeling through Stochastic Differential Equations/Score-Based Generative Modeling through Stochastic Differential Equations.md
          - Upscale-A-Video, Temporal-Consistent Diffusion Model for Real-World Video Super-Resolution: 论文阅读/Diffusion/Upscale-A-Video, Temporal-Consistent Diffusion Model for Real-World Video Super-Resolution/Upscale-A-Video, Temporal-Consistent Diffusion Model for Real-World Video Super-Resolution.md
          - Unleashing the Power of One-Step Diffusion based Image Super-Resolution via a Large-Scale Diffusion Discriminator: 论文阅读/Diffusion/Unleashing the Power of One-Step Diffusion based Image Super-Resolution/Unleashing the Power of One-Step Diffusion based Image Super-Resolution.md
          - DOVE, Efficient One-Step Diffusion Model for Real-World Video Super-Resolution: 论文阅读/Diffusion/DOVE, Efficient One-Step Diffusion Model for Real-World Video Super-Resolution/DOVE, Efficient One-Step Diffusion Model for Real-World Video Super-Resolution.md
extra:
  generator: false #是否删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Abiesjqq
      name: Abies on Github
    - icon: fontawesome/brands/github
      link: https://github.com/Noflowerzzk
      name: Noflower on Github

  #   - icon: fontawesome/brands/weixin
  #     link: https://s1.imagehub.cc/images/2024/02/02/bb9ee71b03ee7a3b87caad5cc4bcebff.jpeg
  #     name: Wechat
  #   - icon: fontawesome/brands/telegram
  #     link: https://t.me/wecowin
  #     name: telegram
  #   - icon: fontawesome/brands/x-twitter #联系方式图标 : https://fontawesome.com/ 去这里找图标
  #     link: https://twitter.com/wcowin_
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/Wcowin

  #   - icon: fontawesome/regular/envelope #联系方式图标
  #     link: mailto:<wangkewen821@gmail.com> #邮件联系方式
  #   - icon: fontawesome/brands/bilibili
  #     link: https://space.bilibili.com/1407028951/lists/4566631?type=series
  # analytics:
  #   provider: google #谷歌分析
  #   property:  ##如果你 clone 了my模板，请将这个修改为你的

  #   # 网页底部反馈
  #   feedback:
  #     title: 此页面有帮助吗？
  #     ratings:
  #       - icon: material/thumb-up-outline #图标可自定义
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           谢谢你的反馈！
  #       - icon: material/thumb-down-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >-
  #           Thanks for your feedback! Help us improve this page by
  #           using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  # cookies设置（可选）
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
  #     如果你同意,你可以帮助我们让我们的网站更好

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  # - callouts
  - md_in_html
  - markdown.extensions.abbr # 支持Markdown文件上方自定义标题标签等
  - pymdownx.magiclink
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.highlight:
      linenums: true
      auto_title: true
      anchor_linenums: true
  #      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_generator:
        !!python/name:pymdownx.emoji.to_svg # 用 SVG 图标显示 emoji


  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  # - tabs.js
  # - javascripts/extra.js
  # - javascripts/extra2.js
  # - javascripts/bannerSlider.js
  - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/extra.js # extra的cdn
  - javascripts/animate-details.js
  - javascripts/mathjax.js
  - javascripts/cursor.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/busuanzi.pure.mini.js
  #  - https://cdn.jsdelivr.net/npm/busuanzi@2.3.0/dist/busuanzi.pure.mini.js
  # - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6

  # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/js/social-share.min.js
  # - javascripts/backbound1.js
  # - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js
  # - https://res.zvo.cn/translate/translate.js  # Translate
  - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/view.js
  # - javascripts/font-loader.js
  # - javascripts/toc-sync.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/extra2.css
  - stylesheets/cursor.css # 鼠标指针
  - stylesheets/info.css # 阅读信息等 info 对象
  - stylesheets/create_and_update.css # 创建时间和更新时间样式
  # - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/stylesheets/extra.css
  # - stylesheets/link.css  #友链
  # - stylesheets/poem.css
  # - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/stylesheets/poem.css
  # - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/stylesheets/link.css  #友链
  # - stylesheets/card2.css
  # - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/stylesheets/card2.css
  - stylesheets/customize.css #按钮圆角化
  # - stylesheets/homepage.css  # 首页居中
  # - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/stylesheets/customize.css  #按钮圆角化
  # - stylesheets/flink.css
  # - stylesheets/bannerSlider.css
  # - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/stylesheets/extra.css # extra.css的CDN
  # - stylesheets/extra1.css
  # - stylesheets/video.css
  # - https://unpkg.com/@waline/client@v2/dist/waline.css
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css #评论
  # - ckplayer/css/ckplayer.css
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css  #字体
  # - https://static.zeoseven.com/zsft/292/main/result.css #字体
  # - stylesheets/ziti.css  #字体
  #  - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/stylesheets/ziti.css
  # - https://chinese-fonts-cdn.deno.dev/packages/lxgwwenkai/dist/LXGWWenKai-Bold/result.css
  - stylesheets/font.css # 把远程 css 换成本地版本
  # - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css # font-awesome表情支持
  # - stylesheets/timeline.css
  # - stylesheets/LiquidGlass.css
  - https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined

plugins:
  - search
  - git-committers:
      enabled: true
      #    enabled: !ENV [ git-committers, false ]
      repository: Abiesjqq/Abies_Notebook
      branch: main
  - git-revision-date-localized:
      enabled: true
      #    enabled: !ENV [ git-revision-date-localized, false ]
      type: iso_date
      enable_creation_date: true
  - blog:
      blog_dir: notices
      blog_toc: true
      post_date_format: full
      archive_toc: true
      categories_toc: true
      #      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      #      pagination: true
      #      pagination_keep_content: true
      #      draft_if_future_date: true
      pagination_per_page: 5
#  - mkdocs-jupyter # 对 jupyter notebook 的支持
